language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 9c6558805c8a00ef83371f4dcd82bfc765d2eac147a7442164f8cc1b401d43de
install:
  - npm run bootstrap
script: npm run tsc_lint_test
after_success:
  - npx codeclimate-test-reporter < ./coverage/lcov.info
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e8f45655cff8_key -iv $encrypted_e8f45655cff8_iv
    -in .travis/id_rsa.enc -out .travis/id_rsa -d
deploy:
  - provider: script
    script: NPM_TAG=$NPM_TAG bash .travis/deploy.sh
    api_key:
      secure: JDw06YX4/egO+WjuWVHsEcPS/04syh6fEpY1RbQgEypFNDt8UVvHXPcSP6nNp2YDvfbAWF1TBKojBJk02EQDB1KlQgnO/csvq3tBOSlQU0Cku6zKcUX6LzywLuBPfc3gYKTeXsiNly31vmMxTh2hwHnx2iYxHdMN7CojQpf1JdI=
    on:
      branch: [latest, next]
      repo: taye/interact.js
